STRING_COLUMNS = [
    'PREFIXTTL',
    'INDIVIDUALNAME',
    'FIRSTNAME',
    'MIDDLENAME',
    'LASTNAME',
    'ADDRESS',
    'ADDRESS2LINE',
    'CITY',
]

DD2_COLUMNS = [
    'PREFIXTTL',
    'INDIVIDUALNAME',
    'FIRSTNAME',
    'MIDDLENAME',
    'LASTNAME',
    'ADDRESS',
    'ADDRESS2LINE',
    'CITY',
    'STATE',
    'NETWORTHPREM',
    '#7641_1: Income Code - Estimated Household - 100% - Income',
    '#7641_2: Income Code - Estimated Household - 100% - Precision Level',
    '#7840: Boat Owner',
    '#2350: Business Owner',
    '#7723: Celebrities',
    '#9350: Economic Stability Indicator',
    '#8337: Highly Likely Investors',
    '#8438: Home Market Value - Estimated - Ranges (RP)',
    '#8642: Home Market Value - Estimated',
    '#9750: Home Market Value - Estimated - Actual (RP)',
    '#8201: Income - Estimated Household - Higher Ranges',
    '#8641: Income - Estimated Household',
    '#2067: Investing - Active',
    '#7793: Investments - Personal',
    '#7794: Investments - Real Estate',
    '#7795: Investments - Stocks / Bonds',
    '#2800: Investors - Stocks Bonds - PLUS',
    '#7847: NASCAR',
    '#8479: NetWorth',
    '#9356: NetWorth - Gold',
    '#8637: Occupation - Input Individual',
    '#8667: Occupation - 3rd Individual',
    '#8668: Occupation - 4th Individual',
    '#8669: Occupation - 5th Individual',
    '#2360: Occupation - Detail - Input Individual',
    '#8276: Upscale Living',
    'Estimated Disposable Income (B) (Financial)',
    'Estimated Disposable Income Index (B) (Financial)',
    'Estimated Net Worth (B) (Financial)',
    'AP001287_Retirement_Assets_Fin_dollar_ap001287',
    'AP001288_Premium_Plus_Self_Directed_Investor_investor_ap001288',
    'AP001370_Total_Liquid_Investible_Assets_V2_dollar_beggc284',
    'AP004306_Proportion_of_Assets_in__Trusts_output_ap004306',
    'AP004947_Household_Owns_A_Vacation_Weekend_Home_Fin_rank_base_20_AP004947',
    'AP005200_Likely_To_Switch_Investment_Provider_Fin_rank_base_20_AP005200',
    'AP005428_Annuities_Acquired_in_the_Last_Twelve_Months_Fin_rank_base_20_AP005428'
]

CATEGORICAL_COLUMNS = [
    'STATE',
    'NETWORTHPREM',
    '#7641_2: Income Code - Estimated Household - 100% - Precision Level',
    '#2350: Business Owner',
    '#8337: Highly Likely Investors',
    '#8438: Home Market Value - Estimated - Ranges (RP)',
    '#8642: Home Market Value - Estimated',
    '#8201: Income - Estimated Household - Higher Ranges',
    '#9356: NetWorth - Gold',
    '#8637: Occupation - Input Individual',
    '#8667: Occupation - 3rd Individual',
    '#8668: Occupation - 4th Individual',
    '#8669: Occupation - 5th Individual',
    '#2360: Occupation - Detail - Input Individual'
]

data_mappings = {
    'PREFIXTTL': 'prefix',
    'INDIVIDUALNAME': 'INDIVIDUALNAME',
    'FIRSTNAME': 'first_name',
    'MIDDLENAME': 'MIDDLENAME',
    'LASTNAME': 'last_name',
    'ADDRESS': 'address',
    'ADDRESS2LINE': 'ADDRESS2LINE',
    'CITY': 'CITY',
    'STATE': 'STATE',
    'NETWORTHPREM': 'NETWORTHPREM',
    '#8688: Gender - Input Individual': 'Gender',
    '#8623_1: Date of Birth - Input Individual (YYYY/MM) - Year': 'Age',
    '#7641_1: Income Code - Estimated Household - 100% - Income': 'Income Code-Estimated Household-100%-Income',
    '#7641_2: Income Code - Estimated Household - 100% - Precision Level': 'Income Code-Estimated Household-100%-Precision Level',
    '#7840: Boat Owner': 'Boat Owner',
    '#2350: Business Owner': 'Business Owner',
    '#7723: Celebrities': 'Celebrities',
    '#9350: Economic Stability Indicator': 'Economic Stability Indicator',
    '#8337: Highly Likely Investors': 'Highly Likely Investors',
    '#8438: Home Market Value - Estimated - Ranges (RP)': 'Home Market Value-Estimated-Ranges (RP)',
    '#8642: Home Market Value - Estimated': 'Home Market Value-Estimated',
    '#9750: Home Market Value - Estimated - Actual (RP)': 'Home Market Value-Estimated-Actual (RP)',
    '#8201: Income - Estimated Household - Higher Ranges': 'Income-Estimated Household-Higher Ranges',
    '#8641: Income - Estimated Household': 'Income-Estimated Household',
    '#2067: Investing - Active': 'Investing-Active',
    '#7793: Investments - Personal': 'Investments-Personal',
    '#7794: Investments - Real Estate': 'Investments-Real Estate',
    '#7795: Investments - Stocks / Bonds': 'Investments-Stocks or Bonds',
    '#2800: Investors - Stocks Bonds - PLUS': 'Investors-Stocks Bonds-PLUS',
    '#7847: NASCAR': 'NASCAR',
    '#8479: NetWorth': 'NetWorth',
    '#9356: NetWorth - Gold': 'NetWorth-Gold',
    '#8637: Occupation - Input Individual': 'Occupation-Input Individual',
    '#8667: Occupation - 3rd Individual': 'Occupation-3rd Individual',
    '#8668: Occupation - 4th Individual': 'Occupation-4th Individual',
    '#8669: Occupation - 5th Individual': 'Occupation-5th Individual',
    '#2360: Occupation - Detail - Input Individual': 'Occupation-Detail-Input Individual',
    '#8276: Upscale Living': 'Upscale Living',
    'Estimated Disposable Income (B) (Financial)': 'Estimated Disposable Income (B) (Financial)',
    'Estimated Disposable Income Index (B) (Financial)': 'Estimated Disposable Income Index (B) (Financial)',
    'Estimated Net Worth (B) (Financial)': 'Estimated Net Worth (B) (Financial)',
    'AP001287_Retirement_Assets_Fin_dollar_ap001287': 'Retirement Assets',
    'AP001288_Premium_Plus_Self_Directed_Investor_investor_ap001288': 'Premium Plus Self Directed Investor',
    'AP001370_Total_Liquid_Investible_Assets_V2_dollar_beggc284': 'Total Liquid Investible Assets',
    'AP004306_Proportion_of_Assets_in__Trusts_output_ap004306': 'Proportion of Assets in Trusts',
    'AP004947_Household_Owns_A_Vacation_Weekend_Home_Fin_rank_base_20_AP004947': 'Household_Owns A Vacation Weekend Home',
    'AP005200_Likely_To_Switch_Investment_Provider_Fin_rank_base_20_AP005200': 'Likely To Switch Investment Provider',
    'AP005428_Annuities_Acquired_in_the_Last_Twelve_Months_Fin_rank_base_20_AP005428': 'Annuities  Acquired in the Last Twelve Months',
}
